config/routes.rb
Rails.application.routes.draw do
  root to: 'images#index'
  resources :images, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    @image.update_attributes(image_params)
    if @image.save
      redirect_to image_url(@image)
    else
      render :edit
    end
  end

  def show
    @image = Image.find(params[:id])
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to root_url
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<h1>Image編集</h1>
<%= form_with model: @image, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <p><%= form.submit %></p>
<% end %>

app/views/images/index.html.erb
<h1>Images一覧</h1>
<div>
  <%= link_to "新規作成", new_image_path %>
</div>
<% @images.each do |image| %>
  <h2><%= image.name %></h2>
  <%= link_to "詳細", image_path(image) %>
  <%= link_to "削除", image_path(image), method: :delete %>
<% end %>

app/views/images/new.html.erb
<h1>Image作成</h1>
<%= form_tag("/images/create", {multipart: true}) do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @image.name %>">
          <p>画像</p>
          <input image="image" type="file" value="<%= @image.name %>">
         
          <input type="submit" value="新規登録">
        <% end %>

app/views/images/show.html.erb
<h1>Image詳細</h1>
<h2><%= @image.name %></h2>
<p><%= link_to "編集", edit_image_path(@image) %></p>
<p><%= link_to "戻る", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageUploadApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>